module.exports = {
	// various
	firebaseURL: "https://fiery-inferno-569.firebaseio.com",

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
	AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

	// UI FEEDBACK ACTIONS
	DISPLAY_ERROR: "DISPLAY_ERROR",
	DISPLAY_MESSAGE: "DISPLAY_MESSAGE",
	DISMISS_FEEDBACK: "DISMISS_FEEDBACK",

	// Project action types
	LOADED_ALL_PROJECTS: "LOADED_ALL_PROJECTS",
	INSERTED_NEW_PROJECT: "INSERTED_NEW_PROJECT",
	DELETED_PROJECT: "DELETED_PROJECT",

	// Task action types
	LOADED_ALL_TASKS: "LOADED_ALL_TASKS",
	INSERTED_NEW_TASK: "INSERTED_NEW_TASK",
	DELETED_TASK: "DELETED_TASK",

	// USERS
	LOADED_ALL_USERS: "LOADED_ALL_USERS"
};